In [1]:
import pandas as pd

In [3]:
batters = pd.read_csv("../data/processed/batter_ft.csv")
bowlers = pd.read_csv("../data/processed/bowler_ft.csv")

In [5]:
batters.shape, bowlers.shape

((17708, 23), (13878, 17))

In [7]:
batters.head(5)

,match_id,date,venue,innings,team,opp,batter,runs,balls,fours,...,SR,avg_runs,sr,avg_balls,avg_venue_runs,avg_opp_runs,avg_4s,avg_6s,boundary_pct,avg_out
0,548346,2012-04-29,Wankhede Stadium,1,Deccan Chargers,Mumbai Indians,A Ashish Reddy,10,10,0,...,100.0,0.00,0.0,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.00
1,548352,2012-05-04,"MA Chidambaram Stadium, Chepauk",2,Deccan Chargers,Chennai Super Kings,A Ashish Reddy,3,3,0,...,100.0,10.00,100.0,10.00,0.0,0.0,0.000000,1.000000,0.10000,1.00
2,548359,2012-05-08,"Rajiv Gandhi International Stadium, Uppal",2,Deccan Chargers,Kings XI Punjab,A Ashish Reddy,8,8,1,...,100.0,6.50,100.0,6.50,0.0,0.0,0.000000,0.500000,0.05000,1.00
3,548373,2012-05-18,"Rajiv Gandhi International Stadium, Uppal",2,Deccan Chargers,Rajasthan Royals,A Ashish Reddy,10,4,2,...,250.0,7.00,100.0,7.00,8.0,0.0,0.333333,0.333333,0.07500,1.00
4,548376,2012-05-20,"Rajiv Gandhi International Stadium, Uppal",1,Deccan Chargers,Royal Challengers Bangalore,A Ashish Reddy,4,5,0,...,80.0,7.75,137.5,6.25,9.0,0.0,0.750000,0.250000,0.18125,0.75

In [8]:
bowlers.head()

,match_id,date,venue,innings,opp,team,bowler,balls,runs,wkts,overs,econ,avg_wkts,avg_eco,avg_runs_given,avg_venue_wkts,avg_opp_wkts
0,548341,2012-04-26,Subrata Roy Sahara Stadium,2,Deccan Chargers,Pune Warriors,A Ashish Reddy,24,32,2,4.00,8.00,0.000000,0.000000,0.00,0.0,0.000000
1,548346,2012-04-29,Wankhede Stadium,2,Deccan Chargers,Mumbai Indians,A Ashish Reddy,14,11,1,2.33,4.72,2.000000,8.000000,32.00,0.0,2.000000
2,548348,2012-05-01,Barabati Stadium,2,Deccan Chargers,Pune Warriors,A Ashish Reddy,19,32,1,3.17,10.09,1.500000,6.360000,21.50,0.0,1.500000
3,548352,2012-05-04,"MA Chidambaram Stadium, Chepauk",1,Deccan Chargers,Chennai Super Kings,A Ashish Reddy,13,16,1,2.17,7.37,1.333333,7.603333,25.00,0.0,1.333333
4,548356,2012-05-06,M Chinnaswamy Stadium,2,Deccan Chargers,Royal Challengers Bangalore,A Ashish Reddy,25,36,1,4.17,8.63,1.250000,7.545000,22.75,0.0,1.250000

In [10]:
batters[['batter', 'date', 'runs', 'avg_runs', 'sr', 'avg_balls', 'avg_venue_runs', 'avg_opp_runs', 'avg_4s', 'avg_6s','boundary_pct', 'avg_out']].head()

,batter,date,runs,avg_runs,sr,avg_balls,avg_venue_runs,avg_opp_runs,avg_4s,avg_6s,boundary_pct,avg_out
0,A Ashish Reddy,2012-04-29,10,0.00,0.0,0.00,0.0,0.0,0.000000,0.000000,0.00000,0.00
1,A Ashish Reddy,2012-05-04,3,10.00,100.0,10.00,0.0,0.0,0.000000,1.000000,0.10000,1.00
2,A Ashish Reddy,2012-05-08,8,6.50,100.0,6.50,0.0,0.0,0.000000,0.500000,0.05000,1.00
3,A Ashish Reddy,2012-05-18,10,7.00,100.0,7.00,8.0,0.0,0.333333,0.333333,0.07500,1.00
4,A Ashish Reddy,2012-05-20,4,7.75,137.5,6.25,9.0,0.0,0.750000,0.250000,0.18125,0.75

In [16]:
bowlers[['bowler', 'wkts', 'runs', 'avg_wkts', 'avg_runs_given', 'avg_eco', 'avg_venue_wkts', 'avg_opp_wkts']].sample(5)

,bowler,wkts,runs,avg_wkts,avg_runs_given,avg_eco,avg_venue_wkts,avg_opp_wkts
293,A Nehra,1,33,0.4,26.4,7.698,0.0,0.0
7581,MW Short,0,7,0.0,9.0,6.500,0.0,0.0
3912,Harpreet Brar,0,20,0.0,24.4,8.114,0.0,0.0
1424,Arshdeep Singh,0,39,1.6,44.0,10.324,0.0,1.6
9463,R Sai Kishore,4,33,1.0,27.0,7.944,0.0,1.0

In [17]:
batters.isnull().sum()

match_id          0
date              0
venue             0
innings           0
team              0
opp               0
batter            0
runs              0
balls             0
fours             0
sixes             0
team_score        0
outs              0
SR                0
avg_runs          0
sr                0
avg_balls         0
avg_venue_runs    0
avg_opp_runs      0
avg_4s            0
avg_6s            0
boundary_pct      0
avg_out           0
dtype: int64

In [18]:
bowlers.isnull().sum()

match_id          0
date              0
venue             0
innings           0
opp               0
team              0
bowler            0
balls             0
runs              0
wkts              0
overs             0
econ              0
avg_wkts          0
avg_eco           0
avg_runs_given    0
avg_venue_wkts    0
avg_opp_wkts      0
dtype: int64